# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-20 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Document name')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(unique=True, verbose_name='Url')),
                ('documents', models.ManyToManyField(related_name='urls', to='crawler.Document', verbose_name='Document')),
            ],
        ),
    ]
